### ISSUE TITLE
Clarify the licencing situation for the library

### ISSUE THREAD

**Issue by jarhodes314** [ozziexsh/bankroll#2]
I'd love to use this, but the licencing situation is rather unclear. The [bling docs](https://hexdocs.pm/bling/readme.html) describe Bankroll as "free". The generated README in the downloaded package instructs me to "purchase a licence", but the link for that takes me to https://github.com/ozziexsh/bankroll and the project README does not mention anything about licensing.

Please could you clarify the situation?

**Comment by ozziexsh** [comment]
Bankroll used to be a paid product but I did not have time to push it further so I decided to open source it. You can use it for free!

Thanks for letting me know about the wording, I'll make sure it gets updated
